name: memcached_client
version: 0.1.0
description: >
  A Memcached client library written in Dart language.
authors:
- Henri Chen <henrichen@rikulo.org>
homepage: http://rikulo.org
dependencies:
  unittest:
  logging:
